[package]
name = "wasm-inject"
version = "0.1.0"
edition = "2021"
authors = ["Yuta Saito <kateinoigakukun@gmail.com>"]
license = "MIT"
publish = false

[dependencies]
walrus = "0.20.3"
anyhow = "1.0.75"

[dev-dependencies]
wasmparser = "0.118.1"
wasmprinter = "0.2.75"
