[package]
name = "ruby_wasm"
version = "0.0.0"
edition = "2021"
authors = ["Yuta Saito <kateinoigakukun@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.6.2"
wizer = "3.0.0"
wasmtime-wasi = "9.0.4"
wasi-cap-std-sync = "9.0.4"
wasm-inject = { path = "../../packages/crates/wasm-inject" }
# wasi-vfs-cli = { git = "https://github.com/kateinoigakukun/wasi-vfs/", tag = "v0.5.0" }
wasi-vfs-cli = { path = "/home/katei/ghq/github.com/kateinoigakukun/wasi-vfs/crates/wasi-vfs-cli" }
