name: Prune Actions caches

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - run: rake ci:prune_caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
